name: Events Demo 1
on: 
  pull_request: 
    types:
      - opened
    branches: 
      - main
  workflow_dispatch:
  push: 
    branches:
      - main
      - 'dev-*' # * - all characters (no slashes)
      - 'feat/**' # ** - all characters (with slashes)
    paths-ignore:
      - '.github/workflows/*' # push activates if we target one of this branched but we dont change the files in .github/workflows/
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."